#!/usr/bin/env python3
"""Regenerate tokens.css and tokens.py from tokens.json."""
import json
import textwrap
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "tokens.json"


def load() -> dict:
    return json.loads(SRC.read_text())


def generate_css(tokens: dict) -> str:
    c = tokens["color"]
    t = tokens["typography"]
    lines = [
        "/* Generated by generate.py — edit tokens.json, not this file */",
        "",
        ":root {",
        "  /* Typography */",
    ]
    for k, v in t.items():
        prop = k.replace("scale", "text-").replace("lineHeight", "line-height-").replace("fontMono", "font-mono").replace("fontMonoBold", "font-mono-bold")
        prop = "".join(["-" + ch.lower() if ch.isupper() else ch for ch in prop]).lstrip("-")
        lines.append(f"  --{prop}: {v['value']};")

    lines += ["", "  /* Light theme (default) */"]
    for k, v in c["light"].items():
        prop = "".join(["-" + ch.lower() if ch.isupper() else ch for ch in k]).lstrip("-")
        comment = f"  /* {v['comment']} */" if "comment" in v else ""
        lines.append(f"  --color-{prop}: {v['value']};{comment}")

    lines += ["}", "", ".theme-dark {"]
    for k, v in c["dark"].items():
        prop = "".join(["-" + ch.lower() if ch.isupper() else ch for ch in k]).lstrip("-")
        lines.append(f"  --color-{prop}: {v['value']};")
    lines.append("}")

    lines += ["", "/* Data viz shade tokens */", ":root {"]
    for k, v in c["dataviz"].items():
        prop = "".join(["-" + ch.lower() if ch.isupper() else ch for ch in k]).lstrip("-")
        comment = f"  /* {v['comment']} */" if "comment" in v else ""
        lines.append(f"  --{prop}: {v['value']};{comment}")
    lines.append("}")

    return "\n".join(lines) + "\n"


def generate_py(tokens: dict) -> str:
    c = tokens["color"]
    t = tokens["typography"]
    lines = [
        '"""Generated by generate.py — edit tokens.json, not this file."""',
        "",
        "LIGHT = {",
    ]
    for k, v in c["light"].items():
        lines.append(f'    "{k}": "{v["value"]}",')
    lines += ["}", "", "DARK = {"]
    for k, v in c["dark"].items():
        lines.append(f'    "{k}": "{v["value"]}",')
    lines += ["}", "", "DATAVIZ = {"]
    for k, v in c["dataviz"].items():
        lines.append(f'    "{k}": "{v["value"]}",')
    lines += ["}", "", "TYPOGRAPHY = {"]
    for k, v in t.items():
        lines.append(f'    "{k}": "{v["value"]}",')
    lines += [
        "}",
        "",
        "TAG_HUES = " + repr(tokens["tag"]["hues"]),
        "",
        '# Tag color formulas:',
        '#   solid:      f"hsl({hue}, 55%, 42%)"',
        '#   chip bg:    f"hsla({hue}, 45%, 55%, 0.06)"',
        '#   chip border:f"hsla({hue}, 35%, 45%, 0.25)"',
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    tokens = load()
    (ROOT / "tokens.css").write_text(generate_css(tokens))
    (ROOT / "tokens.py").write_text(generate_py(tokens))
    print("Generated tokens.css and tokens.py")
