"""Generated by generate.py — edit tokens.json, not this file."""

LIGHT = {
    "background": "#F5F4F1",
    "surface": "#ECE9E4",
    "surface2": "#E3DFD8",
    "border": "#D1CCC4",
    "text": "#1A1A18",
    "textMuted": "#6D6A64",
    "textFaint": "#98938A",
    "accent": "#D97A32",
    "accentSubdued": "rgba(217, 122, 50, 0.22)",
    "interactive": "#5F8A3B",
    "interactiveSubdued": "rgba(95, 138, 59, 0.18)",
    "analytic": "#7A4FB3",
    "critical": "#B6423C",
}

DARK = {
    "background": "#141412",
    "surface": "#1C1C19",
    "surface2": "#262521",
    "border": "#3A3832",
    "text": "#E8E2D8",
    "textMuted": "#A7A093",
    "textFaint": "#7C766C",
    "accent": "#E08A43",
    "accentSubdued": "rgba(224, 138, 67, 0.22)",
    "interactive": "#91B85A",
    "interactiveSubdued": "rgba(145, 184, 90, 0.18)",
    "analytic": "#A47DDB",
    "critical": "#E06A63",
}

DATAVIZ = {
    "shadePanel": "#ECE9E4",
    "shadeAlternate": "#E3DFD8",
    "shadeReferenceBand": "#D1CCC4",
    "shadeUncertainty": "#DDD2E8",
    "shadeContext": "#EAE6DE",
    "shadeHighlight": "#F1D8C4",
}

TYPOGRAPHY = {
    "fontMono": "'GeistMono-Regular', Consolas, monaco, monospace",
    "fontMonoBold": "'GeistMono-Bold', Consolas, monaco, monospace",
    "scaleH1": "32px",
    "scaleH2": "20px",
    "scaleBody": "16px",
    "scaleMeta": "12px",
    "scaleUi": "12px",
    "scaleTag": "12px",
    "lineHeightUi": "1.25",
    "lineHeightProse": "1.42",
}

TAG_HUES = [0, 10, 18, 28, 38, 75, 95, 115, 135, 270, 285, 300, 315, 335, 345]

# Tag color formulas:
#   solid:      f"hsl({hue}, 55%, 42%)"
#   chip bg:    f"hsla({hue}, 45%, 55%, 0.06)"
#   chip border:f"hsla({hue}, 35%, 45%, 0.25)"
