"""
Compute WCAG 2.1 contrast ratios for all meaningful color pairs and write
accessibility.md. Run whenever tokens change.
"""
from pathlib import Path
import json, math

ROOT = Path(__file__).parent.parent

# ── Contrast math ──────────────────────────────────────────────────────────────

def _linearize(c: float) -> float:
    return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4

def luminance(hex_color: str) -> float:
    h = hex_color.lstrip("#")
    r, g, b = (int(h[i:i+2], 16) / 255 for i in (0, 2, 4))
    return 0.2126 * _linearize(r) + 0.7152 * _linearize(g) + 0.0722 * _linearize(b)

def contrast(fg: str, bg: str) -> float:
    l1, l2 = luminance(fg), luminance(bg)
    hi, lo = max(l1, l2), min(l1, l2)
    return (hi + 0.05) / (lo + 0.05)

def grade(ratio: float) -> str:
    if ratio >= 7.0:  return "AAA"
    if ratio >= 4.5:  return "AA"
    if ratio >= 3.0:  return "AA Large"
    return "Fail"

def badge(ratio: float) -> str:
    g = grade(ratio)
    return {"AAA": "✅ AAA", "AA": "✅ AA", "AA Large": "⚠️ AA Large", "Fail": "❌ Fail"}[g]

# ── Load tokens ────────────────────────────────────────────────────────────────

tokens = json.loads((ROOT / "tokens/tokens.json").read_text())

def hex(theme: dict, key: str) -> str:
    return theme[key]["value"]

L = tokens["color"]["light"]
D = tokens["color"]["dark"]

# ── Pairs to evaluate ──────────────────────────────────────────────────────────
# (label, fg_key, bg_key)

TEXT_PAIRS = [
    ("text",       "text"),
    ("text-muted", "textMuted"),
    ("text-faint", "textFaint"),
    ("accent",     "accent"),
    ("interactive","interactive"),
    ("analytic",   "analytic"),
    ("critical",   "critical"),
]

SURFACE_PAIRS = [
    ("background", "background"),
    ("surface",    "surface"),
    ("surface-2",  "surface2"),
]

# Semantic color as background (for badges, alerts, filled elements)
SEMANTIC_BG = [
    ("accent",      "accent"),
    ("interactive", "interactive"),
    ("analytic",    "analytic"),
    ("critical",    "critical"),
]

def build_table(theme: dict, label: str) -> list[str]:
    lines = [f"### {label}", ""]

    # Text colors on neutral surfaces
    lines += [
        "**Text on surfaces**",
        "",
        "| Foreground | Background | Ratio | Grade |",
        "|---|---|---|---|",
    ]
    for fg_label, fg_key in TEXT_PAIRS:
        if fg_key not in theme:
            continue
        for bg_label, bg_key in SURFACE_PAIRS:
            if bg_key not in theme:
                continue
            fg_hex = theme[fg_key]["value"]
            bg_hex = theme[bg_key]["value"]
            if fg_hex.startswith("rgba"):
                continue
            r = contrast(fg_hex, bg_hex)
            lines.append(f"| {fg_label} `{fg_hex}` | {bg_label} `{bg_hex}` | {r:.2f}:1 | {badge(r)} |")

    lines += [""]

    # Text/background on semantic color fills (badges, alerts)
    lines += [
        "**Text on semantic fills** (badges, alerts, filled elements)",
        "",
        "| Foreground | Background | Ratio | Grade |",
        "|---|---|---|---|",
    ]
    for bg_label, bg_key in SEMANTIC_BG:
        if bg_key not in theme:
            continue
        bg_hex = theme[bg_key]["value"]
        # white-equivalent (background) and black-equivalent (text) on the semantic fill
        for fg_label, fg_key in [("text", "text"), ("background", "background")]:
            if fg_key not in theme:
                continue
            fg_hex = theme[fg_key]["value"]
            r = contrast(fg_hex, bg_hex)
            lines.append(f"| {fg_label} `{fg_hex}` | {bg_label} `{bg_hex}` | {r:.2f}:1 | {badge(r)} |")

    lines += [""]
    return lines


# ── Write accessibility.md ─────────────────────────────────────────────────────

out = [
    "# Accessibility — WCAG 2.1 Contrast Ratios",
    "",
    "Generated by `scripts/generate_a11y.py`. Re-run whenever `tokens/tokens.json` changes.",
    "",
    "**Thresholds**",
    "- ✅ **AAA** — ≥ 7:1 — enhanced (body text ideal)",
    "- ✅ **AA** — ≥ 4.5:1 — minimum for normal text",
    "- ⚠️ **AA Large** — ≥ 3:1 — minimum for large text (18px+ or 14px bold)",
    "- ❌ **Fail** — below 3:1 — do not use for text",
    "",
    "Note: muted and faint text tokens are intentionally lower-contrast and should",
    "only be used for non-essential metadata at 12px+, never for primary content.",
    "",
]

out += build_table(L, "Light theme")
out += build_table(D, "Dark theme")

(ROOT / "accessibility.md").write_text("\n".join(out))
print("→ accessibility.md")
